[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.7" }
simula_core = { path = "../../crates/simula_core" }
simula_camera = { path = "../../crates/simula_camera" }
simula_viz = { path = "../../crates/simula_viz" }
rand = "0.8.4"
bevy-inspector-egui = "0.10"

fj = { git = "https://github.com/hannobraun/Fornjot.git", rev = "ad7e8082949cb4907d7429b29af2df43b34b0c09" }
